name: buf-release
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "push the tag label to BSR"
        run: |
          set -euo pipefail
          echo ${{ secrets.BUF_TOKEN }} | buf registry login --token-stdin
          buf push --label ${{ github.ref_name }}
        working-directory: ./proto